### ISSUE TITLE
_

### ISSUE THREAD

**Issue by KAY9791top** [cloudwindy/yander-python#1]
我是之前给你上课的曹老师，可能后面是另一个老师来给你们上课了。你也应该了解，你们学校的水平相对比较落后的，所以后面这个课程开展的内容可能会相对比较简单，所以以你现在的水平没必要学这些东西。建议你可以查阅一下有什么高中生可以参加的一些计算机比赛参加一下，相信你可以的！如果有任何问题欢迎加我微信13817441819

**Comment by cloudwindy** [comment]
别这样，这是公开场合。。。
