### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by StinkiTofu** [cloudwindy/yander-python#2]
请问一下，下载下来运行的时候总会显示“主程序: 发生了错误:” 。代码没改过，只在config改了一下end参数。是我少装了什么插件吗？
![屏幕截图 2021-07-13 175606](https://user-images.githubusercontent.com/56662884/125432176-a7672f45-36e5-44eb-80fc-f918ebb16620.png)

谢谢作者

**Comment by cloudwindy** [comment]
您好，您提供的信息太少，没办法判断出具体问题的位置。能否提供一下config.json的内容，十分感谢。

**Comment by StinkiTofu** [comment]
> 您好，您提供的信息太少，没办法判断出具体问题的位置。能否提供一下config.json的内容，十分感谢。

您好，谢谢您抽空回复
![2](https://user-images.githubusercontent.com/56662884/127732358-dde16052-5933-47c2-a491-78dbf9897604.png)
我只修改了start和end，我看代码好像是download那里不知道怎么就跳出去了
小白刚开始没多久，多多包涵

**Comment by cloudwindy** [comment]
已经上传UI模块修复的版本，请别忘了备份您的config.json，然后下载最新版本。
这次您将看到完整的错误提示，请继续跟进回复，感谢。

**Comment by StinkiTofu** [comment]
谢谢，但似乎不行。UIPrinter没有exception这个对象，还出现多个异常
![屏幕截图 2021-07-31 200431](https://user-images.githubusercontent.com/56662884/127740254-0f03c930-5ac4-4e55-a5db-46a1332353b1.png)
不好意思打扰您了

**Comment by cloudwindy** [comment]
78892d96082ef83818d26cc8c8422a029cbe4008 显示错误的问题已经修复，但是我认为在截图中出错的main.py第321行，可能是网络出现问题了，请检查一下代理，如果带上代理之后仍然有问题，请再回复。

如果问题已解决，请关闭。
